name: Automated tests
on: 
  push:
    paths:
      - 'src/**'
      - '.github/*.yaml'
      - 'package.json'
      - 'package-lock.json'
      - '.eslintrc.json'

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:14.15.4

    services:
      couchdb:
        image: couchdb:2.3.1
        ports:
        - 5984:5984

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: development
          PORT: 3000
          LOG_LEVEL: info
          COUCHDB_URL: http://localhost:5984
          USE_COUCH_AUTH: false
          COUCHDB_USER: admin
          COUCHDB_PASSWORD: admin
          BASE_URL: http://localhost:3000
          UPLOAD_LIMIT: 1mb          
          NDEX_API_URL: https://dev.ndexbio.org/v2
          NDEX_TEST_USER: testtesttest
          NDEX_TEST_PASSWORD: 123123123
