FROM node:14

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .
RUN NODE_ENV=development npm ci # dev b/c we need dev deps
RUN NODE_ENV=production npm run build # build the clientside app in prod mode

EXPOSE 3000

CMD npm run start # run the server
